// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const sanitizeEnvValue = (value?: string) => value?.trim().replace(/^['\"]|['\"]$/g, '');

const rawSupabaseUrl = sanitizeEnvValue(import.meta.env.VITE_SUPABASE_URL as string | undefined);
const projectId = sanitizeEnvValue(import.meta.env.VITE_SUPABASE_PROJECT_ID as string | undefined);

const normalizeSupabaseUrl = (url?: string) => {
  if (!url) return undefined;
  if (url.startsWith('http://') || url.startsWith('https://')) return url;
  return `https://${url}`;
};

const SUPABASE_URL = normalizeSupabaseUrl(rawSupabaseUrl) ??
  (projectId ? `https://${projectId}.supabase.co` : undefined);
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const AUTH_PERSISTENCE_PREFERENCE_KEY = 'tracetech.auth.remember-me';

const isBrowser = typeof window !== 'undefined';

const safeGetStorage = (storageType: 'local' | 'session') => {
  if (!isBrowser) return null;
  try {
    return storageType === 'local' ? window.localStorage : window.sessionStorage;
  } catch {
    return null;
  }
};

const shouldRememberSession = () => {
  const storage = safeGetStorage('local');
  if (!storage) return true;
  return storage.getItem(AUTH_PERSISTENCE_PREFERENCE_KEY) !== 'false';
};

const adaptiveAuthStorage = {
  getItem: (key: string): string | null => {
    const preferredStorage = shouldRememberSession() ? safeGetStorage('local') : safeGetStorage('session');
    const fallbackStorage = shouldRememberSession() ? safeGetStorage('session') : safeGetStorage('local');
    return preferredStorage?.getItem(key) ?? fallbackStorage?.getItem(key) ?? null;
  },
  setItem: (key: string, value: string): void => {
    const preferredStorage = shouldRememberSession() ? safeGetStorage('local') : safeGetStorage('session');
    const fallbackStorage = shouldRememberSession() ? safeGetStorage('session') : safeGetStorage('local');
    preferredStorage?.setItem(key, value);
    fallbackStorage?.removeItem(key);
  },
  removeItem: (key: string): void => {
    safeGetStorage('local')?.removeItem(key);
    safeGetStorage('session')?.removeItem(key);
  },
};

export const authSessionPreferences = {
  getRememberMe: () => shouldRememberSession(),
  setRememberMe: (rememberMe: boolean) => {
    const storage = safeGetStorage('local');
    if (!storage) return;
    storage.setItem(AUTH_PERSISTENCE_PREFERENCE_KEY, rememberMe ? 'true' : 'false');
  },
};

export const getAuthEmailRedirectUrl = () => {
  const envRedirect = import.meta.env.VITE_AUTH_EMAIL_REDIRECT_URL as string | undefined;
  if (envRedirect && envRedirect.trim().length > 0) {
    return envRedirect;
  }
  if (!isBrowser) {
    return undefined;
  }

  const appBase = import.meta.env.BASE_URL || '/';
  const normalizedBase = appBase.endsWith('/') ? appBase : `${appBase}/`;
  return new URL(`auth`, `${window.location.origin}${normalizedBase}`).toString();
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: adaptiveAuthStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});